services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 10s ; python3 ./app.py"
    depends_on:
      - mysql
    
  mysql:
    build: ./mysql/
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: 'root_p@ss_1'
      MYSQL_DATABASE: 'test_db'
    ports:
      - '3306:3306'